//
//  AppTexts.swift
//  FitNutCoach
//
//  Created by Anupam Kumar Lal on 24/08/25.
//

import UIKit

class AppTexts {

    static let appName = "FitNutCoach"
    
    static let hiText = "Hi"
    static let kcalText = "kcal"
    static let litreText = "L"
    static let logMealText = "Log Meal"
    static let startWorkoutText = "Start Workout"
    static let proteinText = "Protein"
    static let carbsText = "Carbs"
    static let fatText = "Fat"
    static let caloriesText = "Calories"
    static let nextMealIdeasText = "Next Meal Ideas"
    static let nWorkoutsThisWeekText = "%@ workouts this week"
    static let keepItUpText = "Keep it up 💪"
    static let noWorkoutsYetText = "No workouts yet!"
    static let startItTodayText = "Start it today!"
    
    static let logWaterIntakeText = "Log Water Intake"
    static let trackYourHyrdrationText = "Track your hydration for today"
    static let twoFiftyMLText = "+250 ml"
    static let saveText = "Save"
    static let cancelText = "Cancel"
    
    static let chooseMealOptionText = "Choose how you want to log your meal"
    static let snapAPhotoText = "Snap a Photo"
    static let useAItoDetectFoodsText = "Use AI to detect foods"
    static let scanABarCodeText = "Scan a Barcode"
    static let foodViaBarcodeText = "Find foods via barcode"
    static let addManuallyText = "Add Manually"
    static let searchOrCreateFoodText = "Search or create your food"
    
    static let alignThebarcodeText = "Align the barcode within the frame"
    static let enterBarcodeManuallyText = "Enter Barcode Manually"
    static let enterBarcodeText = "Enter barcode"
    static let confirmText = "Confirm"
    
    static let breakFastText = "Breakfast"
    static let lunchText = "Lunch"
    static let dinnerText = "Dinner"
    static let snacksText = "Snacks"
    static let editText = "Edit"
    static let deleteText = "Delete"
    
    static let breakFastDescriptionText = "🥖 A good day begins with breakfast — log yours now."
    static let lunchDescriptionText = "🍚 Strong afternoons need the right lunch — add it in."
    static let dinnerDescriptionText = "🫓 Balance your day — don’t skip dinner tracking."
    static let snacksDescriptionText = "🍎 Smart snacking counts — record yours here."
    
    static let confirmFoodText = "Confirm Food"
    static let confirmAndAddText = "Confirm and Add"
    static let dailyGoalsText = "Daily Goals"
    static let servingSizeText = "Serving Size"
    static let measurementUnitText = "Measurement Unit"
    static let numberOfServingsText = "Number of Servings"
    static let mealText = "Meal"
    static let updateText = "Update"
    
    static let frequentlyTrackedFoodsText = "Frequently Tracked Foods"
    static let historyText = "History"
    static let searchFoodText = "Search food item by name"
    static let addFoodItemText = "Add Food Item"
    static let servings = "servings"
    
    static let noFoodItemFoundText = "No food item found"
    static let noHistoryFoundText = "No history found"
    static let someMoreFoodAddedText = "%@ more food added"
    static let addedText = "added"
    static let logForText = "Log For %@"
    static let snapText = "Snap"
    
    static let identifyingFoodText = "Identifying food..."
    static let detectedFoodsText = "Detected Foods"
    static let selectTheClosestFoodItemText = "Select the closest food item"
    static let notSatisfiedWithTheDetectionText = "Not satisfied with the detection?"
    static let detectWithAIText = "Detect with AI (%@ left for today)"
    static let detectedUsingAIText = "Detected using AI"
    
    static let pleaseSelectTheMealTypeText = "Please select the type of meal you want to log."
    static let selectMealTypeText = "Select Meal Type"
    static let selectedMealType = "Selected Meal Type"
    
    static let clearText = "Clear"
    static let partlyCloudyText = "Partly Cloudy"
    static let cloudyText = "Cloudy"
    static let rainText = "Rain"
    static let drizzleText = "Drizzle"
    static let thunderstormText = "Thunderstorm"
    static let snowText = "Snow"
    static let fogText = "Fog"
    static let uvLowText = "Low"
    static let uvModerateText = "Moderate"
    static let uvHighText = "High"
    static let uvVeryHighText = "Very High"
    static let uvExtremeText = "Extreme"
    static let feelsLikeText = "Feels like"
    static let humidityText = "Humidity"
    static let windSpeedText = "Wind Speed"
    static let uvIndexText = "UV Index"
    static let precipitationText = "Precipitation"
    static let sunriseText = "Sunrise"
    static let sunsetText = "Sunset"
    static let currentConditionsText = "Current Conditions"
    static let fiveDayForecastText = "5-Day Forecast"
    static let lastUpdatedText = "Last updated at:"
    
    // Nudges
    static let nudgesTitleText = "Nudges"
    static let nudgeHealthScoreText = "Today's Health Score"
    static let nudgeSmartNudgesTodayText = "%@ Smart Nudges Today"
    static let nudgeCompletedPendingText = "%@ Completed | %@ Pending"
    static let nudgePrioritySectionText = "Priority Nudges"
    static let nudgeAllSectionText = "All Nudges"
    static let nudgeCompletedSectionText = "Completed Nudges"
    static let nudgeMarkCompletedText = "Mark Done"
    static let nudgeDismissText = "Dismiss"
    static let nudgeViewDetailsText = "View Details"
    static let nudgeNoActiveText = "You're all caught up for now!"
    static let nudgeGeneratedAtText = "Generated at %@"
    
    static let nudgeCategoryHydrationText = "Hydration"
    static let nudgeCategoryNutritionText = "Nutrition"
    static let nudgeCategoryActivityText = "Activity"
    static let nudgeCategoryWorkoutText = "Workout"
    static let nudgeCategorySleepText = "Sleep"
    static let nudgeCategoryWeightText = "Weight"
    static let nudgeCategoryWeatherText = "Weather"
    static let nudgeCategoryRecoveryText = "Recovery"
    static let nudgeCategoryMealLoggingText = "Meal Logging"
    static let nudgeCategoryAchievementText = "Achievement"
    
    static let nudgePriorityHighText = "High"
    static let nudgePriorityMediumText = "Medium"
    static let nudgePriorityLowText = "Low"
    
    static let nudgeMotivationExcellentText = "Excellent progress today — keep the momentum going!"
    static let nudgeMotivationGoodText = "You're doing well — a few more healthy choices will boost your score."
    static let nudgeMotivationFairText = "Small steps add up — let's pick one nudge to tackle next."
    static let nudgeMotivationLowText = "Every healthy habit starts with one action — let's begin today."
    
    static let nudgeActionDrinkWaterText = "Drink Water"
    static let nudgeActionEatProteinText = "Eat Protein"
    static let nudgeActionWalkMoreText = "Walk More"
    static let nudgeActionLogWeightText = "Log Weight"
    static let nudgeActionStartWorkoutText = "Start Workout"
    static let nudgeActionLogMealText = "Log Meal"
    
    static let nudgeHydrationLowTitleText = "Hydration Boost"
    static let nudgeHydrationLowMessageText = "You're behind on water today. Drink %@L more to stay on track."
    static let nudgeHydrationHotTitleText = "Hot Weather Alert"
    static let nudgeHydrationHotMessageText = "It's %@ outside. Drink extra water to stay hydrated."
    static let nudgeHydrationAfternoonTitleText = "Afternoon Hydration"
    static let nudgeHydrationAfternoonMessageText = "It's been a while since you logged water. Take a quick hydration break."
    
    static let nudgeProteinGapTitleText = "Protein Goal Close"
    static let nudgeProteinGapMessageText = "You're only %@g away from your protein goal."
    static let nudgeLowCaloriesTitleText = "Calorie Check"
    static let nudgeLowCaloriesMessageText = "Your calorie intake is low today. Add a balanced meal to fuel your day."
    
    static let nudgeLowStepsTitleText = "Move More"
    static let nudgeLowStepsMessageText = "Your step count is below target. A short walk can help you catch up."
    static let nudgeEveningWalkTitleText = "Evening Walk"
    static let nudgeEveningWalkMessageText = "A quick 15-minute walk will help you reach today's target of %@ steps."
    static let nudgeInactivityTitleText = "Break Inactivity"
    static let nudgeInactivityMessageText = "You've been inactive today. Stand up and move for a few minutes."
    
    static let nudgeWorkoutReminderTitleText = "Workout Reminder"
    static let nudgeWorkoutReminderMessageText = "You haven't logged a workout today. Even a short session counts."
    static let nudgeRestDayTitleText = "Consider a Rest Day"
    static let nudgeRestDayMessageText = "You've logged multiple workouts today. Recovery is part of progress."
    static let nudgeWorkoutDoneTitleText = "Workout Logged"
    static let nudgeWorkoutDoneMessageText = "Great job completing a workout today. Keep the streak alive!"
    
    static let nudgeBedtimeTitleText = "Bedtime Reminder"
    static let nudgeBedtimeMessageText = "It's getting late. Consistent sleep supports recovery and energy."
    static let nudgePoorSleepTitleText = "Sleep Trend"
    static let nudgePoorSleepMessageText = "Your logged sleep is below 6 hours. Aim for better rest tonight."
    
    static let nudgeLogWeightTitleText = "Log Your Weight"
    static let nudgeLogWeightMessageText = "Update your weight to track progress accurately."
    
    static let nudgeRecoveryTitleText = "Recovery Time"
    static let nudgeRecoveryConsecutiveMessageText = "Multiple workouts logged — prioritize recovery today."
    static let nudgeStretchTitleText = "Stretch & Recover"
    static let nudgeStretchMessageText = "You've exercised a lot today. A stretching session can help recovery."
    
    static let nudgeRainTitleText = "Rainy Day Tip"
    static let nudgeRainMessageText = "Rain expected — consider an indoor workout or carry a jacket."
    static let nudgeColdTitleText = "Cold Weather Tip"
    static let nudgeColdMessageText = "It's chilly outside. Layer up and warm up properly before activity."
    static let nudgeHeatTitleText = "Heat Advisory"
    static let nudgeHeatMessageText = "It's %@ — hydrate more and consider shifting intense workouts to morning."
    
    static let nudgeMissingBreakfastTitleText = "Log Breakfast"
    static let nudgeMissingBreakfastMessageText = "You haven't logged breakfast yet. Start your day with a balanced meal."
    static let nudgeMissingLunchTitleText = "Log Lunch"
    static let nudgeMissingLunchMessageText = "Lunch isn't logged yet. Keep your nutrition tracking consistent."
    static let nudgeMissingDinnerTitleText = "Log Dinner"
    static let nudgeMissingDinnerMessageText = "Don't forget to log dinner to complete your daily nutrition picture."
    
    static let nudgeCalorieGoalTitleText = "Calorie Goal Achieved"
    static let nudgeCalorieGoalMessageText = "You've hit your calorie target today. Well done!"
    static let nudgeProteinGoalTitleText = "Protein Goal Achieved"
    static let nudgeProteinGoalMessageText = "You've reached your protein goal. Great nutrition discipline!"
    static let nudgeWaterGoalTitleText = "Hydration Goal Achieved"
    static let nudgeWaterGoalMessageText = "You've met your water target today. Stay hydrated!"
    static let nudgeStepsGoalTitleText = "Step Goal Achieved"
    static let nudgeStepsGoalMessageText = "You've reached your step goal. Keep moving!"
    
    // Profile
    static let profileTitleText = "Profile"
    static let editProfileText = "Edit Profile"
    static let personalInfoText = "Personal Info"
    static let dailyTargetsText = "Daily Targets"
    static let accountText = "Account"
    static let logoutText = "Logout"
    static let saveProfileText = "Save Profile"
    static let nameText = "Name"
    static let emailText = "Email"
    static let dateOfBirthText = "Date of Birth"
    static let heightText = "Height"
    static let weightText = "Weight"
    static let dietTypeText = "Diet Type"
    static let allergiesText = "Allergies"
    static let calorieTargetText = "Calorie Target"
    static let proteinTargetText = "Protein Target"
    static let carbTargetText = "Carb Target"
    static let fatTargetText = "Fat Target"
    static let waterTargetText = "Water Target"
    static let stepTargetText = "Step Target"
    static let cmText = "cm"
    static let kgText = "kg"
    static let stepsText = "steps"
    static let gramsText = "g"
    static let dietVegText = "Vegetarian"
    static let dietNonVegText = "Non-Vegetarian"
    static let dietVeganText = "Vegan"
    static let profileSaveFailedText = "Could not save profile. Please try again."
    static let profileSaveSuccessText = "Profile updated successfully."
    static let noneText = "None"
    
}

class ErrorTexts {
    static let invalidEmailFormat = "Invalid email format"
    static let somethingWentWrong = "Something went wrong. Please try again later."
    static let noProductsFound = "No product found."
}
